### PR TITLE
Southwind Airlines (TC-GRY)

### PR DESCRIPTION
**Pull request by yelloyelloman**

### CODE REVIEW

**Comment by hamzaelasmar** [comment]
How can you do this???? This looks so beatuiful and much more better than my liveries,
Also, are you in the planes discord?

**Comment by yelloyelloman** [comment]
to be honest, i have no idea and yes i am in the planes discord

**Comment by remenkemi** [comment]
I'll merge it once i take a look (since the icons aren't pictures of your livery, I don't know what it looks like and when a new painter makes a pull request we check it)

**Comment by yelloyelloman** [comment]
Ah ok, Thanks

**Comment by hamzaelasmar** [comment]
hey can you tell me your discord user?, I will also try to generate the icons  for u

**Comment by remenkemi** [comment]
> hey can you tell me your discord user?, I will also try to generate the icons  for u

You (or anyone) can just download the livery, go to livery picking menu in xplane, and click the generate icons button.

**Comment by yelloyelloman** [comment]
will generate icons later on, thanks for the info i needed

**Pull request merged**
