### PR TITLE
Turkmenistan Airlines (EZ-A777) is done!

### PR DESCRIPTION
**Pull request by hamzaelasmar**
also if you can add me on the description of the repo (if you can)

### CODE REVIEW

**Comment by remenkemi** [comment]
I can't do it right now (on my phone) but you can go ahead and add it yourself

**Comment by hamzaelasmar** [comment]
Thank You :) ok i will add it rn do the second thing

**Comment by hamzaelasmar** [comment]
@remenkemi i cant

**Comment by remenkemi** [comment]
> @remenkemi i cant

Did it in your fork and it will automatically add it to the pull request

**Comment by hamzaelasmar** [comment]
@remenkemi i still cant see it

**Comment by remenkemi** [comment]
Don't worry I'll do it later

**Pull request merged**
