### PR TITLE
Southwind Airlines (TC-GRY) [COMPLETED]

### PR DESCRIPTION
**Pull request by yelloyelloman**

### CODE REVIEW

**Comment by remenkemi** [comment]
Did you mean to include the Etihad livery in this pull request?
Southwing looks great! If you meant for the Etihad to be here I'll merge the pull request.
Also, quick thing about the Etihad livery:
image
image
The silver looks like it's supposed to fade rather than have that abrupt line (sorry for low quality images)

**Comment by yelloyelloman** [comment]
yeah but will fix the etihad livery if can, i will fix the silver color as you said.

**Comment by yelloyelloman** [comment]
Screenshot 2023-12-02 225749

comparison with my livery and irl [might not needed anyways]

**Comment by remenkemi** [comment]
I see, I guess it was just the lighting in that image! The only other thing I really notice off is  
image
image
I can merge it anyway but that's my suggestion for you to fix.

**Comment by yelloyelloman** [comment]
Screenshot 2023-12-02 231327
ok, have made changes to the color let me know if the color is still off

**Comment by remenkemi** [comment]
I don't think the color is really off, just the shape. Notice how the orange meets the corner of the silver part in the photo.
image
image
Also I noticed one more detail, I think the Arabic font is different
image
image

**Comment by yelloyelloman** [comment]
ok. will fix the arabic font as you said then i will add the updated fuselage

**Comment by yelloyelloman** [comment]
i cannot find exactly what the arabic font is unfortunately, but ill still add the updated fuselage in 2 minutes

**Comment by yelloyelloman** [comment]
Screenshot 2023-12-03 135304
image
A6-ETG both sides

**Comment by remenkemi** [comment]
I merged it with only the southwind livery, please let me know when etihad is ready and i'll merge! thanks!

**Pull request merged**
